import { readFileSync } from "fs"
import type { Subscription } from "./types.js"

type Threshold = NonNullable<Subscription["threshold"]>
type IconName = "tornado" | "wave" | "storm" | "snow" | "alert"

// PNG assets live at the repo root (assets/icons) and are generated by
// scripts/generate-icons.mjs. Resolve relative to this module so the path
// holds whether we run from src/ or the compiled dist/ output.
const ICON_DIR = new URL("../assets/icons/", import.meta.url)

const dataUriCache = new Map<string, string>()

function pngDataUri(fileName: string): string {
  const cached = dataUriCache.get(fileName)
  if (cached) {
    return cached
  }

  const base64 = readFileSync(new URL(fileName, ICON_DIR)).toString("base64")
  const uri = `data:image/png;base64,${base64}`
  dataUriCache.set(fileName, uri)
  return uri
}

function pickIcon(eventName: string): IconName {
  if (/tornado|funnel/i.test(eventName)) return "tornado"
  if (/flood|surge|tsunami|marine|coastal|rip current|seiche|water/i.test(eventName)) return "wave"
  if (/snow|winter|blizzard|ice|icy|sleet|freez|frost|wind chill|cold/i.test(eventName)) return "snow"
  if (/storm|thunder|hurricane|tropical|wind|hail|lightning/i.test(eventName)) return "storm"
  return "alert"
}

/** Builds the Teams webhook payload (Adaptive Card wrapped in a message attachment). */
export function buildTeamsMessage(locationName: string, feature: any, threshold?: Threshold) {
  const tier: Threshold = threshold ?? "Advisory"
  const icon = pngDataUri(`${pickIcon(feature.event ?? "")}-${tier}.png`)

  const event: string = feature.event ?? "Weather Alert"
  const headline: string | undefined = feature.headline
  const description: string | undefined = feature.description
  const instruction: string | undefined = feature.instruction

  const body: unknown[] = [
    {
      type: "ColumnSet",
      columns: [
        {
          type: "Column",
          width: "auto",
          verticalContentAlignment: "center",
          items: [{ type: "Image", url: icon, width: "40px", altText: event }],
        },
        {
          type: "Column",
          width: "stretch",
          items: [
            { type: "TextBlock", text: event, weight: "Bolder", size: "Large", wrap: true },
            { type: "TextBlock", text: locationName, spacing: "None", isSubtle: true, wrap: true },
          ],
        },
      ],
    },
  ]

  if (headline) {
    body.push({ type: "TextBlock", text: headline, wrap: true, spacing: "Medium" })
  }

  const details: unknown[] = []
  if (description) {
    details.push({ type: "TextBlock", text: description, wrap: true })
  }
  if (instruction) {
    details.push({ type: "TextBlock", text: "Instructions", weight: "Bolder", wrap: true, spacing: "Medium" })
    details.push({ type: "TextBlock", text: instruction, wrap: true })
  }

  const actions: unknown[] = []
  if (details.length > 0) {
    body.push({ type: "Container", id: "details", isVisible: false, items: details, spacing: "Medium" })
    actions.push({
      type: "Action.ToggleVisibility",
      title: "Show details",
      targetElements: ["details"],
    })
  }

  const card: Record<string, unknown> = {
    $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
    type: "AdaptiveCard",
    version: "1.5",
    body,
  }
  if (actions.length > 0) {
    card.actions = actions
  }

  return {
    type: "message",
    attachments: [
      {
        contentType: "application/vnd.microsoft.card.adaptive",
        content: card,
      },
    ],
  }
}
